### ISSUE TITLE
can't sign up or sign in to the service

### ISSUE THREAD

**Issue by wiki-me** [learn-awesome/learn#221]
i tried to signed up using only email , and got some error, then tried to sign up again but it tells me the user already exists.

so i try to sign in using the email and password, and now i get this  error whenever i try to sign in again (when just clicking on the "sign-in" button in the homepage):

![learn_awesome_error](https://user-images.githubusercontent.com/68199012/97783085-01911480-1b9e-11eb-8ed9-1e2af73458dd.png)

I tried to delete the cookies of the website and log in again, it does not work.

I also tried to use different browsers when debugging this.

**Comment by eshnil** [comment]
@wiki-me Thanks for reporting the issue.

LearnAwesome automatically assigns a nickname to every new user based on what Auth0 provides. In case of email signups, Auth0 picks the first part of the email address. However, LearnAwesome needs the nickname to be at least 4 characters. It's possible that the username part of your email address was shorter than 4 characters, so while signup on Auth0 was successful, login on LearnAwesome keeps failing because it cannot create a User record.

Was this your case? If so, can you try now as I have pushed a fix for handling this correctly (by appending random digits to get a valid nickname)

If this was not the case, do you mind sharing your email address to help me debug the issue? You can DM on [Twitter](https://twitter.com/nileshtrivedi) or [Slack](https://learnawesome.org/join_slack).

**Comment by eshnil** [comment]
Length must be with 4 to 30 characters. This is the regular expression nicknames must satisfy: `/\A[a-zA-Z][a-zA-Z0-9\_.\-]+\Z/`

I see another possible issue. Your nickname must begin with an alphabetic character. I suspect your nickname begins with a digit, and that would fail the validation for nickname. I will push a fix for handling such cases.

**Comment by wiki-me** [comment]
Thanks it seems to be working now, when i tried to change the nickname it kept giving these unclear errors, until i tried to remove spaces from the nickname which seem to be the problem (along with the unclear error message), but that is a seperate issue (i can open another issue if you would like).
