### ISSUE TITLE
Fix icons

### ISSUE THREAD

**Issue by nileshtrivedi** [learn-awesome/learn#28]
Fix / Change icons for:
- Browse by topic
- Browse by format
- Search
- About
- and others

**Comment by sankalp0o** [comment]
Listing down ideas for icons

Browse by topic - The current icon works
Browse by format - https://thenounproject.com/term/media/1370823
Search - Current icon works
About - https://thenounproject.com/term/about/2510068
Random - https://thenounproject.com/term/random/1406897
Dashboard - https://thenounproject.com/term/home/2691554

**Comment by Ash0703** [comment]
Hey all,

PFA the icons list for left panel nav. I suggest keeping the icon size 18px to 24px. But you can explore and see what works. Also , since we're using the UI kit, we could stick to the colours used for the existing screens. 

1. Dashboard - https://thenounproject.com/search/?q=dashboard&i=2801498
2. Search - https://thenounproject.com/search/?q=search&i=731296
3. Browse by Topic - https://thenounproject.com/search/?q=topic&i=2409443
4. Browse by Format - https://thenounproject.com/search/?q=media&i=1370823
5. Random Item - https://thenounproject.com/search/?q=item&i=2420047
6. Random Topic - https://thenounproject.com/search/?q=random&i=2028720
7. Advanced Search - https://thenounproject.com/search/?q=lightening&i=721933
8. About - https://thenounproject.com/search/?q=about&i=1876966
9. Whats New - https://thenounproject.com/search/?q=update&i=370571

Let me know if you face any issues!

**Comment by eshnil** [comment]
@Ash0703 Perfect!

It looks like NounProject only lets us download 700px by 700px versions. Also, the images have attribution text which needs to be clipped off. Can you please convert all these icons to the right size and commit in this directory? https://github.com/learn-awesome/learn/tree/master/public/nounproject

I will then include these in the layout.

**Comment by Ash0703** [comment]
Sure, I'll send it today
