### ISSUE TITLE
visiting https://learnawesome.org/item_types/course breaks the application

### ISSUE THREAD

**Issue by virajvchavan** [learn-awesome/learn#95]
Maybe because we have too many items under item_type 'course'

**Comment by eshnil** [comment]
Heroku has a 30 seconds limit to send response to each request. Solving for #92 should help with this.

**Comment by athityakumar** [comment]
I would like to take this up for Hacktoberfest. Can you please assign this issue to me?

So, while caching may be one way to solve this, another way could be to paginate the response. So that, we have something like `/item_types/course?page=1&per_page=25`. But we'd also need to add the ui element to showcase pagination. WDYT?

**Comment by eshnil** [comment]
@athityakumar Yes, pagination will be better. But need to think about the UI and sort order to make it most meaningful for the user. Think of a solution that you would be happy with as a user yourself.

**Comment by athityakumar** [comment]
Sure thing, I've posted on the Gitter channel as well! 😄

**Comment by eshnil** [comment]
There are bugs in the query or pagination code. This page: https://learnawesome.org/item_types/audio

Shows not only non-audio items but also topics are repeated multiple times.

**Comment by eshnil** [comment]
Seems to be working fine now. 👍
